[package]
name = "medians"
version = "0.0.4"
authors = ["Libor Spacek"]
edition = "2021"
description = "Median, Statistical Measures, Mathematics, Statistics"
readme = "README.md"
homepage = "https://github.com/liborty/medians"
repository = "https://github.com/liborty/medians"
license = "BSD-3-Clause"
keywords = ["statistics","median"]
categories = ["science","mathematics","algorithms"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
anyhow = "^1"
indxvec = "^1"
[dev-dependencies]
devtimer = "^4"
ran = "^0.2"
