name: test

on: push

jobs:
  build:  
    name: medians 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --release -- --test-threads=1 --nocapture --color always        
